### ISSUE TITLE
[Ресурс] Перевод создания зеркала для FDroid

### ISSUE THREAD

**Issue by kiriharu** [WeArchivingInternet/HowTo#16]
# Тип проблемы:
- Я хочу изменить ресурс или информацию о ресурсе

# Описание
На всякий случай было бы хорошо перевести информацию с [офф. гайда](https://f-droid.org/en/docs/Running_a_Mirror/) по созданию зеркала FDroid

**Comment by eweto** [comment]
#24 перевёл

**Comment by kiriharu** [comment]
Сделано в #24
