### ISSUE TITLE
[Ресурс] Как выгрузуить весь Pypi (пакеты для Python)

### ISSUE THREAD

**Issue by MadL1me** [WeArchivingInternet/HowTo#33]
# Тип проблемы:
- Я хочу добавить ресурс  ( Как выгрузуить весь Pypi (пакеты для Python))

# Описание
ИндексPyPi является самым популярным регистром пакетов для python. Подобно Nuget и Nim-пакетам нужно найти способ и добавить инструкцию по выгрузке всего PyPi. Возмонжно придется писать свой скрипт для выгрузки всего этого многопоточно и батчами (потому что на сколько я знаю, pip это делает синхронно и очень медленно), но есть вероятность найти что-то готовое.

**Comment by kiriharu** [comment]
Дубль? См. #12
