### ISSUE TITLE
[Ресурс] Репозитории FDroid

### ISSUE THREAD

**Issue by kiriharu** [WeArchivingInternet/HowTo#7]
# Тип проблемы
- Я хочу добавить ресурс  

# Описание 
FDroid - каталог приложений для операционной системы Android. Главный репозиторий проекта содержит только свободное программное обеспечение.

**Comment by eweto** [comment]
https://f-droid.org/ru/docs/Running_a_Mirror/

**Comment by kiriharu** [comment]
Сделано в #15
